import type { HealthResponse, SnapshotResponse } from "../api";
import type { ProductView, RiskItem } from "./types";
import type { RiskActionMap } from "./useRiskActions";
import { riskKindLabel } from "./riskModel";

export function OverviewWorkspace({ risks, actions, health, snapshot, onView, onRisk }: { risks: RiskItem[]; actions: RiskActionMap; health?: HealthResponse; snapshot?: SnapshotResponse; onView: (view: ProductView) => void; onRisk: (id: string) => void }) {
  const p1 = risks.filter((risk) => risk.priority === "P1").length; const tracked = Object.keys(actions).length; const avgConfidence = risks.length ? Math.round(risks.reduce((sum, risk) => sum + risk.confidence, 0) / risks.length) : 0;
  const byKind = (["coordination", "key-person", "missing-evidence"] as const).map((kind) => ({ kind, count: risks.filter((risk) => risk.kind === kind).length }));
  return <section className="overview-workspace"><header className="overview-hero"><div><span className="eyebrow">Evidence workspace</span><h1>Workspace overview</h1><p>Start with prioritized risks, validate the evidence, then assign follow-up work.</p></div><button onClick={() => onView("risks")} type="button">Review risk inbox</button></header>
    <div className="overview-kpis"><article><span>Open signals</span><strong>{risks.length}</strong><small>Across three evidence lenses</small></article><article className={p1 ? "urgent" : ""}><span>Priority 1</span><strong>{p1}</strong><small>Review before lower-priority signals</small></article><article><span>Average confidence</span><strong>{avgConfidence}%</strong><small>Confidence is not certainty</small></article><article><span>Tracked actions</span><strong>{tracked}</strong><button onClick={() => onView("actions")} type="button">Open actions</button></article></div>
    <div className="overview-grid"><div className="overview-panel"><div className="panel-heading"><div><h2>Top risks</h2><p>Sorted by priority and confidence</p></div><button onClick={() => onView("risks")} type="button">View all</button></div><div className="top-risk-list">{risks.slice(0, 5).map((risk) => <button key={risk.id} onClick={() => onRisk(risk.id)} type="button"><span className={`priority priority-${risk.priority.toLowerCase()}`}>{risk.priority}</span><span><strong>{risk.title}</strong><small>{risk.team} - {risk.confidence}% confidence</small></span><b>{">"}</b></button>)}</div></div>
      <aside className="overview-panel runtime-panel"><div className="panel-heading"><div><h2>Runtime truth</h2><p>What this demo is actually using</p></div></div><dl><div><dt>Analytics engine</dt><dd className={health?.hydra.status === "live" ? "good" : "warn"}>{health?.hydra.status === "live" ? "HydraDB live" : health?.hydra.status === "fallback" ? "Reference fallback" : "Offline"}</dd></div><div><dt>Import mode</dt><dd>{health?.imports_enabled ? "Enabled" : "Read-only"}</dd></div><div><dt>Dataset</dt><dd>{snapshot?.dataset_id ?? "Loading"}</dd></div><div><dt>Coverage</dt><dd className={snapshot?.limitations.length ? "warn" : "good"}>{snapshot?.limitations.length ? `${snapshot.limitations.length} limitations` : "Complete"}</dd></div></dl><button onClick={() => onView("settings")} type="button">Open API & runtime guide</button></aside></div>
    <div className="lens-strip">{byKind.map((item) => <article key={item.kind}><span>{riskKindLabel(item.kind)}</span><strong>{item.count}</strong><p>{item.kind === "coordination" ? "Technical dependencies without a short observed owner path." : item.kind === "key-person" ? "Coordination appears more concentrated than formal roles suggest." : "Expected workflow records absent from the supplied corpus."}</p><button onClick={() => onView("risks")} type="button">Inspect signals</button></article>)}</div>
  </section>;
}
