import type { HealthResponse, SnapshotResponse } from "../api";

const API_BASE = import.meta.env.VITE_XRAY_API_BASE_URL ?? "http://127.0.0.1:8000";
export function SettingsWorkspace({ health, snapshot }: { health?: HealthResponse; snapshot?: SnapshotResponse }) {
  const snapshotId = snapshot?.snapshot_id ?? "{snapshot_id}";
  return <section className="settings-workspace"><header className="section-heading"><div><span className="eyebrow">Operations</span><h1>API & runtime</h1><p>Connect the UI, verify the engine, and understand exactly where data is sent.</p></div></header><div className="settings-grid"><main><section className="settings-card"><h2>Connection</h2><dl><div><dt>API base URL</dt><dd><code>{API_BASE}</code></dd></div><div><dt>Engine</dt><dd>{health?.hydra.status ?? "Checking"}</dd></div><div><dt>Database</dt><dd>{health?.hydra.database ?? "Reference in-memory graph"}</dd></div><div><dt>Mode</dt><dd>{health?.read_only ? "Read-only" : "Read/write"}</dd></div></dl></section>
      <section className="settings-card"><h2>Useful endpoints</h2><p>All finding responses include analysis status, limitations, source, and query provenance.</p><div className="endpoint-list"><code>GET /api/v1/health</code><code>GET /api/v1/snapshots/current</code><code>GET /api/v1/snapshots/{snapshotId}/ghosts</code><code>GET /api/v1/snapshots/{snapshotId}/faultlines</code><code>GET /api/v1/snapshots/{snapshotId}/gaps</code><code>GET /api/v1/snapshots/{snapshotId}/risk-report</code></div></section>
      <section className="settings-card"><h2>Quick API check</h2><pre>{`curl "${API_BASE}/api/v1/snapshots/${encodeURIComponent(snapshotId)}/faultlines?window_days=30"`}</pre><p>A response with <code>source: "fixture"</code> is reference analytics. Only <code>source: "hydradb"</code> plus a non-null executed query proves HydraDB ran that lens.</p></section></main>
      <aside><section className="settings-card"><h2>Data handling</h2><ul><li>The browser calls the API base URL shown here.</li><li>Hosted demo imports are disabled by the API.</li><li>Self-hosted imports stay in the deployment you configure.</li><li>Export only the minimum evidence needed.</li></ul></section><section className="settings-card"><h2>Snapshot facts</h2><dl><div><dt>Dataset</dt><dd>{snapshot?.dataset_id ?? "—"}</dd></div><div><dt>Nodes / edges</dt><dd>{snapshot ? `${snapshot.node_count} / ${snapshot.edge_count}` : "—"}</dd></div><div><dt>Evidence records</dt><dd>{snapshot?.evidence_count ?? "—"}</dd></div></dl></section></aside></div></section>;
}
